services:

  postgres:
    image: postgres:16-alpine
    container_name: pg_example
    volumes:
      - dbdata6:/data/db
    ports:
      - "45432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

volumes:
  dbdata6: