"""common_field can be nullable

Revision ID: 9d660b40fb5c
Revises: a8e1fe58eaca
Create Date: 2025-02-22 10:27:12.677586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d660b40fb5c'
down_revision: Union[str, None] = 'a8e1fe58eaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'common_field',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'common_field',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'common_field',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'common_field',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
